package com.cybershield.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    FAILED_LOGIN,
    CREATE_COMPLAINT,
    UPDATE_COMPLAINT,
    STATUS_CHANGE,
    SEVERITY_CHANGE,
    ASSIGN_INVESTIGATOR,
    UPLOAD_EVIDENCE,
    DOWNLOAD_EVIDENCE,
    CREATE_INVESTIGATION_NOTE,
    REQUEST_INFORMATION,
    PROVIDE_INFORMATION,
    RESOLVE_COMPLAINT,
    CLOSE_COMPLAINT,
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    USER_ENABLED,
    USER_DELETED,
    ADMIN_ACTION
}
