package com.cybershield.enums;

public enum NotificationType {
    COMPLAINT_SUBMITTED,
    COMPLAINT_REVIEWED,
    COMPLAINT_VALIDATED,
    COMPLAINT_REJECTED,
    INVESTIGATOR_ASSIGNED,
    STATUS_CHANGED,
    INFO_REQUESTED,
    INFO_RECEIVED,
    COMPLAINT_RESOLVED,
    COMPLAINT_CLOSED
}
